### ISSUE TITLE
Something wrong with the class files?

### ISSUE THREAD

**Issue by kjaz89** [rezatrue/website-email-retriever#1]
Êþº¾   4 w  Main  java/lang/Object mailList Ljava/util/Set; 	Signature #Ljava/util/Set<Ljava/lang/String;>; 	listofUrl weburl Ljava/lang/String; <clinit> ()V Code  http://yourwebsite.com	   
  LineNumberTable LocalVariableTable <init>
    
 this LMain; main ([Ljava/lang/String;)V  java/util/HashSet
  	     	  " 	  $ WebsiteHandler
 # &  ' (Ljava/lang/String;)V
 # ) * + takingAnchor '(Ljava/lang/String;)Ljava/util/HashSet; - / . 
java/util/Set 0 1 iterator ()Ljava/util/Iterator; 3 5 4 java/util/Iterator 6 7 next ()Ljava/lang/Object; 9 java/lang/String
 # ; < = takeingSourceCode &(Ljava/lang/String;)Ljava/lang/String;
 # ? @ A emailAddressFinder )(Ljava/lang/String;)Ljava/util/ArrayList; - C D E addAll (Ljava/util/Collection;)Z 3 G H I hasNext ()Z	 K M L java/lang/System N O out Ljava/io/PrintStream; Q java/lang/StringBuilder S 
Total Page : 
 P & - V W X size ()I
 P Z [ \ append (I)Ljava/lang/StringBuilder;
 P ^ _ ` toString ()Ljava/lang/String;
 b d c java/io/PrintStream e ' println g Number of Email :  args [Ljava/lang/String; websiteHandler LWebsiteHandler; it Ljava/util/Iterator; link 
sourceCode string LocalVariableTypeTable (Ljava/util/Iterator<Ljava/lang/String;>; 
StackMapTable i 
SourceFile 	Main.java !                	         
       
     &      ³ ±                    
     /     *· ±           
             	      “     Â» Y· ³ » Y· ³ !» #Y² · %L+² ¶ (³ !² !¹ , M§ #,¹ 2 À 8N+-¶ ::² +¶ >¹ B W,¹ F šÿÚ² J» PYR· T² !¹ U ¶ Y¶ ]¶ a² J» PYf· T² ¹ U ¶ Y¶ ]¶ a² ¹ , :§ ¹ 2 À 8N² J-¶ a¹ F šÿç±       B     
      )  2  5  ?  F   U  ^ $ { % ˜ ' ° ( · ' Á +    >    Â h i    £ j k  2  l m  ?  n   F  o   °  p   q     2  l r  s   ! ý 5 # 3ÿ O  t # 3  3    u    v

This is what i retrieve from the class file for Main.class

**Comment by rezatrue** [comment]
If you want to see what's happening in there, open Main.java file : https://github.com/rezatrue/website-email-retriever/blob/master/src/Main.java

**Comment by kjaz89** [comment]
aww. my bad, noob me.
